version: '3.8'

services:
  quad-store-server:
    image: atomgraph/fuseki:4.6
    platform: linux/amd64
    hostname: quad-server
    container_name: quad-server
    env_file:
      - ./env/flexo-mms-quad-store.env
    command: --file=/tmp/mount/cluster.trig --update /ds
    volumes:
      - ./mount:/tmp/mount
    ports:
      - 3030:3030

  layer1-service:
    image: openmbee/flexo-mms-layer1-service:v0.2.0-pre.4
    platform: linux/amd64
    hostname: layer1-service
    container_name: layer1-service
    env_file:
      - ./env/flexo-mms-jwt.env
      - ./env/flexo-mms-layer1.env
    depends_on:
      - quad-store-server
    ports:
      - 8080:8080

  sysmlv2-service:
    image: openmbee/flexo-sysmlv2:omg
    platform: linux/amd64
    hostname: flexo-sysmlv2
    container_name: flexo-sysmlv2
    env_file:
      - ./env/flexo-sysmlv2.env
    depends_on:
      - layer1-service
    ports:
      - 8083:8080

networks:
  default:
    name: flexo-mms-test-network
    driver: bridge